//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivSetup
    {
        public short Sys_No { get; set; }
        public string Sys_NmEN { get; set; }
        public string Sys_NmAR { get; set; }
        public string Exp_Date { get; set; }
        public string Multi_Unit { get; set; }
        public string Multi_Store { get; set; }
        public string Scnd_Grid { get; set; }
        public string OverSea { get; set; }
    }
}
