//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTypes
    {
        public int Actvty_No { get; set; }
        public string Name_Arb { get; set; }
        public string Name_Eng { get; set; }
    }
}
