//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixdAstSalDep
    {
        public short Brn_No { get; set; }
        public long Aset_No { get; set; }
        public string Aset_Nm { get; set; }
        public string Aset_NmEn { get; set; }
        public Nullable<short> Aset_Actvty { get; set; }
        public Nullable<short> Aset_Typ { get; set; }
        public Nullable<decimal> Book_Value { get; set; }
        public string Depr_StDt { get; set; }
        public Nullable<int> DeprSt_No { get; set; }
        public Nullable<decimal> Pursh_Value { get; set; }
        public Nullable<System.DateTime> Pursh_Dt { get; set; }
        public string Pursh_Issue { get; set; }
        public Nullable<long> Acc_DB { get; set; }
        public Nullable<long> Acc_CR { get; set; }
        public string Sup_Nm { get; set; }
        public string Garnt_Cond { get; set; }
        public string Garnt_StDt { get; set; }
        public string Garnt_EndDt { get; set; }
        public string Insur_Issue { get; set; }
        public Nullable<decimal> Insur_Value { get; set; }
        public string Insur_StDt { get; set; }
        public string Insur_EndDt { get; set; }
        public Nullable<short> Loc_No { get; set; }
        public Nullable<int> Aset_Recp { get; set; }
        public string Aset_CmpNo { get; set; }
        public Nullable<decimal> Tot_Depr { get; set; }
        public Nullable<short> Mnth_Depr { get; set; }
        public string AsetCmp_No { get; set; }
        public Nullable<short> DeprSt_No1 { get; set; }
        public Nullable<decimal> Dep_Mnth1 { get; set; }
        public Nullable<decimal> Dep_Mnth2 { get; set; }
        public Nullable<decimal> Dep_Mnth3 { get; set; }
        public Nullable<decimal> Dep_Mnth4 { get; set; }
        public Nullable<decimal> Dep_Mnth5 { get; set; }
        public Nullable<decimal> Dep_Val1 { get; set; }
        public Nullable<decimal> Dep_Val2 { get; set; }
        public Nullable<decimal> Dep_Val3 { get; set; }
        public Nullable<decimal> Dep_Val4 { get; set; }
        public Nullable<decimal> Dep_Val5 { get; set; }
        public Nullable<short> Dep_yer1 { get; set; }
        public Nullable<short> Dep_Yer2 { get; set; }
        public Nullable<short> Dep_Yer3 { get; set; }
        public Nullable<short> Dep_Yer4 { get; set; }
        public Nullable<short> Dep_Yer5 { get; set; }
        public Nullable<long> Ownr_No { get; set; }
        public Nullable<long> Depm_No { get; set; }
        public string Recp_Dt { get; set; }
        public Nullable<short> Ex_Recp { get; set; }
        public Nullable<int> recp_typ { get; set; }
        public Nullable<decimal> Dep_YearPrcnt { get; set; }
        public Nullable<decimal> Dep_MonthPrcnt { get; set; }
        public Nullable<decimal> Dep_NofYear { get; set; }
        public Nullable<decimal> Dep_NofMonth { get; set; }
        public Nullable<System.DateTime> Cancelation_Dt { get; set; }
        public Nullable<short> Cancelation_Typ { get; set; }
        public Nullable<float> Cancelation_Val { get; set; }
        public string Customer_Nm { get; set; }
    }
}
