//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixdAstStatus
    {
        public string AsetStat_NmAr { get; set; }
        public string AsetStat_NmEn { get; set; }
        public short AsetStat_No { get; set; }
    }
}
