//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixdAsetstype
    {
        public short Ac_No1 { get; set; }
        public string Ac_Nm1 { get; set; }
        public Nullable<decimal> Dep_YearPrcnt { get; set; }
        public Nullable<decimal> Dep_MonthPrcnt { get; set; }
        public Nullable<decimal> Dep_NofYear { get; set; }
        public Nullable<decimal> Dep_NofMonth { get; set; }
        public string Cr_Acc { get; set; }
        public Nullable<short> Dep_Prcnt { get; set; }
    }
}
