//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixdAsetsLoc
    {
        public short Loc_No { get; set; }
        public string Loc_Nm { get; set; }
        public string Acc_No { get; set; }
        public Nullable<short> Ownr_No { get; set; }
        public Nullable<long> Acc_DB { get; set; }
        public Nullable<long> Acc_CR { get; set; }
    }
}
