//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAnalytical2
    {
        public long Analytical2_No { get; set; }
        public Nullable<long> Parnt_Acc { get; set; }
        public string Analytical_Nmar { get; set; }
        public string Analytical_Nmen { get; set; }
        public Nullable<short> Level_No { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public Nullable<decimal> Fbal_DB { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
    }
}
