//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAstJrntyp
    {
        public short Jr_Ty { get; set; }
        public string Jrty_Nm { get; set; }
        public string Jrty_NmEn { get; set; }
    }
}
