//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAstbank
    {
        public int ACC_No { get; set; }
        public string Acc_NmAr { get; set; }
        public string Acc_NmEn { get; set; }
        public string Acc_Bank_No { get; set; }
        public Nullable<bool> Rcp_Voucher { get; set; }
        public Nullable<bool> Csh_voucher { get; set; }
        public Nullable<bool> Chk_Voucher { get; set; }
    }
}
