//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLjrntrs
    {
        public short Cmp_No { get; set; }
        public short Brn_No { get; set; }
        public short Jr_Ty { get; set; }
        public long Tr_No { get; set; }
        public short Ln_No { get; set; }
        public Nullable<short> Month_No { get; set; }
        public Nullable<int> Month_Jvno { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<long> Sysub_Account { get; set; }
        public Nullable<System.DateTime> Tr_Dt { get; set; }
        public string Tr_DtAr { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<decimal> Tr_Db { get; set; }
        public Nullable<decimal> Tr_Cr { get; set; }
        public string Dc_No { get; set; }
        public string Tr_Ds { get; set; }
        public string Tr_Ds1 { get; set; }
        public Nullable<long> Clsacc_no1 { get; set; }
        public Nullable<long> Clsacc_no2 { get; set; }
        public Nullable<long> Costcntr_No { get; set; }
        public Nullable<short> Doc_Type { get; set; }
        public string GL_Post { get; set; }
        public string JV_Post { get; set; }
        public string Trf_Post { get; set; }
        public string User_ID { get; set; }
        public string Entr_Dt { get; set; }
        public string Entr_Time { get; set; }
        public Nullable<short> Acc_Type { get; set; }
        public Nullable<decimal> Balnce { get; set; }
        public Nullable<decimal> Tot_DB { get; set; }
        public Nullable<decimal> Tot_CR { get; set; }
        public Nullable<decimal> Tot_Pur { get; set; }
        public Nullable<decimal> Tot_Sal { get; set; }
        public Nullable<decimal> Tot_Disc { get; set; }
        public Nullable<decimal> Bonus_Val { get; set; }
        public Nullable<decimal> Ret_Val { get; set; }
        public Nullable<decimal> Ret_Disc { get; set; }
        public Nullable<decimal> Ret_Bonus { get; set; }
        public Nullable<decimal> Rcpt_Value { get; set; }
        public Nullable<decimal> RetPur_Sal { get; set; }
    }
}
