//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLjrnal
    {
        public short Cmp_No { get; set; }
        public short Brn_No { get; set; }
        public short Jr_Ty { get; set; }
        public long Tr_No { get; set; }
        public Nullable<short> Month_No { get; set; }
        public Nullable<int> Month_Jvno { get; set; }
        public Nullable<short> Doc_Type { get; set; }
        public Nullable<System.DateTime> Tr_Dt { get; set; }
        public string Tr_DtAr { get; set; }
        public string Chq_no { get; set; }
        public string Bnk_Nm { get; set; }
        public Nullable<System.DateTime> Issue_Dt { get; set; }
        public Nullable<System.DateTime> Due_Issue_Dt { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<decimal> Amount_Int { get; set; }
        public Nullable<short> Amount_Frct { get; set; }
        public string Rcpt_By { get; set; }
        public string Pymt_To { get; set; }
        public string Pymt_By { get; set; }
        public string Jv_Post { get; set; }
        public string Trf_Post { get; set; }
        public string User_ID { get; set; }
        public string Entr_Dt { get; set; }
        public string Entr_Time { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<long> TrAcc_No { get; set; }
        public Nullable<long> Cstm_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<long> Emp_No { get; set; }
        public Nullable<decimal> Tr_Db { get; set; }
        public Nullable<decimal> Tr_Cr { get; set; }
    }
}
