//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlLast
    {
        public short Rep_No { get; set; }
        public int Ln_No { get; set; }
        public string Rep_Nm { get; set; }
        public string Rep_Dt { get; set; }
        public Nullable<short> Ln_Ty { get; set; }
        public string ACC_Dsc { get; set; }
        public Nullable<short> Sum_No { get; set; }
        public string Prnt_Sorc { get; set; }
        public Nullable<short> Acc_Ntr { get; set; }
        public Nullable<short> Prnt_YN { get; set; }
        public Nullable<int> Acc_No { get; set; }
        public Nullable<decimal> Prnt_Sorc_Val { get; set; }
        public Nullable<decimal> Acc_Val { get; set; }
    }
}
