//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLMonth
    {
        public short Month_No { get; set; }
        public string Month_GrnmAr { get; set; }
        public string Month_GrnmEn { get; set; }
        public string Month_HjnmAr { get; set; }
        public string Month_HjnmEn { get; set; }
    }
}
