//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glprvyer
    {
        public int Acc_No { get; set; }
        public Nullable<decimal> Prv1_BAL11 { get; set; }
        public Nullable<decimal> Prv1_BAL12 { get; set; }
        public Nullable<decimal> Prv1_BAL13 { get; set; }
        public Nullable<decimal> Prv1_BAL14 { get; set; }
        public Nullable<decimal> Prv1_BAL15 { get; set; }
        public Nullable<decimal> Prv1_BAL16 { get; set; }
        public Nullable<decimal> Prv1_BAL17 { get; set; }
        public Nullable<decimal> Prv1_BAL18 { get; set; }
        public Nullable<decimal> Prv1_BAL19 { get; set; }
        public Nullable<decimal> Prv1_BAL20 { get; set; }
        public Nullable<decimal> Prv1_BAL21 { get; set; }
        public Nullable<decimal> Prv1_BAL22 { get; set; }
        public Nullable<decimal> Prv2_BAL11 { get; set; }
        public Nullable<decimal> Prv2_BAL12 { get; set; }
        public Nullable<decimal> Prv2_BAL13 { get; set; }
        public Nullable<decimal> Prv2_BAL14 { get; set; }
        public Nullable<decimal> Prv2_BAL15 { get; set; }
        public Nullable<decimal> Prv2_BAL16 { get; set; }
        public Nullable<decimal> Prv2_BAL17 { get; set; }
        public Nullable<decimal> Prv2_BAL18 { get; set; }
        public Nullable<decimal> Prv2_BAL19 { get; set; }
        public Nullable<decimal> Prv2_BAL20 { get; set; }
        public Nullable<decimal> Prv2_BAL21 { get; set; }
        public Nullable<decimal> Prv2_BAL22 { get; set; }
        public Nullable<decimal> Prv3_BAL111 { get; set; }
        public Nullable<decimal> Prv3_BAL121 { get; set; }
        public Nullable<decimal> Prv3_BAL131 { get; set; }
        public Nullable<decimal> Prv3_BAL141 { get; set; }
        public Nullable<decimal> Prv3_BAL151 { get; set; }
        public Nullable<decimal> Prv3_BAL161 { get; set; }
        public Nullable<decimal> Prv3_BAL171 { get; set; }
        public Nullable<decimal> Prv3_BAL181 { get; set; }
        public Nullable<decimal> Prv3_BAL191 { get; set; }
        public Nullable<decimal> Prv3_BAL201 { get; set; }
        public Nullable<decimal> Prv3_BAL211 { get; set; }
        public Nullable<decimal> Prv3_BAL221 { get; set; }
        public Nullable<decimal> Budg_DB11 { get; set; }
        public Nullable<decimal> Budg_CR11 { get; set; }
        public Nullable<decimal> Budg_DB12 { get; set; }
        public Nullable<decimal> Budg_CR12 { get; set; }
        public Nullable<decimal> Budg_DB13 { get; set; }
        public Nullable<decimal> Budg_CR13 { get; set; }
        public Nullable<decimal> Budg_DB14 { get; set; }
        public Nullable<decimal> Budg_CR14 { get; set; }
        public Nullable<decimal> Budg_DB15 { get; set; }
        public Nullable<decimal> Budg_CR15 { get; set; }
        public Nullable<decimal> Budg_DB16 { get; set; }
        public Nullable<decimal> Budg_CR16 { get; set; }
        public Nullable<decimal> Budg_DB17 { get; set; }
        public Nullable<decimal> Budg_CR17 { get; set; }
        public Nullable<decimal> Budg_DB18 { get; set; }
        public Nullable<decimal> Budg_CR18 { get; set; }
        public Nullable<decimal> Budg_DB19 { get; set; }
        public Nullable<decimal> Budg_CR19 { get; set; }
        public Nullable<decimal> Budg_DB20 { get; set; }
        public Nullable<decimal> Budg_CR20 { get; set; }
        public Nullable<decimal> Budg_DB21 { get; set; }
        public Nullable<decimal> Budg_CR21 { get; set; }
        public Nullable<decimal> Budg_DB22 { get; set; }
        public Nullable<decimal> Budg_CR22 { get; set; }
    }
}
