//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrAstPymntype
    {
        public short Pymnt_No { get; set; }
        public string Pymnt_NmAr { get; set; }
        public string Pymnt_NmEn { get; set; }
        public Nullable<short> Nof_Emp { get; set; }
    }
}
