//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrAstDeprtmnt
    {
        public int Depm_No { get; set; }
        public string Depm_NmAr { get; set; }
        public string Depm_NmEn { get; set; }
        public string Depm_Lic { get; set; }
        public string Civl_No { get; set; }
        public string Depm_Aprv { get; set; }
    }
}
