//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstSalesman
    {
        public int Slm_No { get; set; }
        public Nullable<int> Brn_No { get; set; }
        public Nullable<int> StoreNo { get; set; }
        public string Slm_NmEn { get; set; }
        public string Slm_NmAr { get; set; }
        public string Slm_Abrv { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Cheqe { get; set; }
        public Nullable<decimal> TCashCheqe { get; set; }
        public Nullable<decimal> Cheqe_UndrPost { get; set; }
        public Nullable<decimal> Difrence { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public Nullable<decimal> CBal { get; set; }
        public Nullable<decimal> BalAgL30 { get; set; }
        public Nullable<decimal> BalAgG30 { get; set; }
        public Nullable<decimal> BalAgG60 { get; set; }
        public Nullable<decimal> BalAgg90 { get; set; }
        public Nullable<decimal> BalAgG120 { get; set; }
        public Nullable<decimal> BalAgG150 { get; set; }
        public Nullable<decimal> BalAgG180 { get; set; }
        public Nullable<decimal> BalAgG270 { get; set; }
        public string Slm_Tel { get; set; }
        public string Slm_Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
