//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstArea
    {
        public short Area_No { get; set; }
        public string Area_NmAR { get; set; }
        public string Area_NmEN { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public Nullable<short> City_No { get; set; }
        public Nullable<short> Slm_No { get; set; }
    }
}
