//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstRefTyp
    {
        public short Main_Reftyp { get; set; }
        public short RefTyp_No { get; set; }
        public string RefTyp_Nm { get; set; }
        public string RefTyp_NmAr { get; set; }
    }
}
