//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstCurncy
    {
        public short Curncy_No { get; set; }
        public string Curncy_Nm { get; set; }
        public Nullable<decimal> Curncy_Rate { get; set; }
        public string Curncy_Nmar { get; set; }
    }
}
