//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstNutrbusn
    {
        public short Nutr_No { get; set; }
        public string Nutr_Nm { get; set; }
        public string Nutr_NmAr { get; set; }
        public string Short_Arb { get; set; }
        public string Short_Eng { get; set; }
    }
}
