//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstwrkPeriod
    {
        public short Period_Time { get; set; }
        public string Period_NmAr { get; set; }
        public string Period_NmEn { get; set; }
        public Nullable<decimal> From_Time { get; set; }
        public Nullable<decimal> To_Time { get; set; }
    }
}
