//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstCustmcatg
    {
        public short Catg_No { get; set; }
        public string Catg_NmAr { get; set; }
        public string Catg_NmEn { get; set; }
        public Nullable<decimal> Credit_Value1 { get; set; }
        public Nullable<decimal> Credit_Value2 { get; set; }
        public Nullable<int> Credit_Days1 { get; set; }
        public Nullable<decimal> Lst_Discount { get; set; }
        public Nullable<int> Lst_Credit_Days { get; set; }
    }
}
