//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItmexpdt
    {
        public short StoreID { get; set; }
        public short Dlv_Stor { get; set; }
        public long Itm_No { get; set; }
        public short Loc_No { get; set; }
        public Nullable<short> Slm_No { get; set; }
        public string Loc_Active { get; set; }
        public string Exp_Date { get; set; }
        public Nullable<int> Catg_No { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<decimal> In_Qty { get; set; }
        public Nullable<decimal> Phy_Qty { get; set; }
        public Nullable<decimal> IsuDLV_Qty { get; set; }
        public Nullable<decimal> BonusPur_Prct { get; set; }
        public Nullable<decimal> Itm_Sal { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> Itm_Cost { get; set; }
        public Nullable<decimal> Disc1_Prct { get; set; }
        public Nullable<decimal> Disc2_Prct { get; set; }
        public Nullable<decimal> DiscSal_Prct { get; set; }
        public Nullable<decimal> DiscSal2_prct { get; set; }
        public Nullable<decimal> BonusSalCrdt_Prct { get; set; }
        public Nullable<decimal> BonusSalCash_Prct { get; set; }
        public Nullable<decimal> OvrItm_Pur { get; set; }
        public Nullable<decimal> OvrItm_Sal { get; set; }
        public Nullable<decimal> OvrDisc1_Prct { get; set; }
        public Nullable<decimal> OvrDisc2_Prct { get; set; }
        public Nullable<decimal> OvrDiscSal_Prct { get; set; }
        public Nullable<decimal> OvrDiscSal2_prct { get; set; }
        public Nullable<decimal> OvrBonusSalCrdt_Prct { get; set; }
        public Nullable<decimal> OvrBonusSalCash_Prct { get; set; }
        public Nullable<decimal> OvrBonusPur_Prct { get; set; }
        public Nullable<decimal> OvrDisc1_Val { get; set; }
        public Nullable<decimal> OvrDisc2_Val { get; set; }
        public Nullable<decimal> OvrBonusPur_Qty { get; set; }
        public Nullable<decimal> OvrBonusPur_Val { get; set; }
        public Nullable<decimal> Phy_Itmcost { get; set; }
        public Nullable<decimal> Phy_Tcost { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public Nullable<decimal> Customs_Prct { get; set; }
        public Nullable<decimal> Customs { get; set; }
        public Nullable<decimal> FcItm_Pur { get; set; }
        public Nullable<decimal> Tot_Expens { get; set; }
        public Nullable<decimal> SExpens { get; set; }
        public Nullable<decimal> Expens1 { get; set; }
        public Nullable<decimal> Expens2 { get; set; }
        public Nullable<decimal> Expens3 { get; set; }
        public Nullable<decimal> Expens4 { get; set; }
        public Nullable<decimal> Expens5 { get; set; }
        public Nullable<decimal> Expens6 { get; set; }
        public Nullable<decimal> Expens7 { get; set; }
        public Nullable<decimal> FcOvrItm_Pur { get; set; }
        public string Batch_No { get; set; }
        public Nullable<decimal> dis_cash_p { get; set; }
        public Nullable<decimal> dis_cash { get; set; }
        public Nullable<decimal> dis_deal_p { get; set; }
        public Nullable<decimal> dis_deal { get; set; }
        public Nullable<decimal> Tot_SalQty { get; set; }
    }
}
