//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItmkind
    {
        public short Kind_No { get; set; }
        public string Kind_Nm { get; set; }
        public string Kind_NmAr { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<decimal> LC_DB { get; set; }
    }
}
