//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLimit_Qty
    {
        public int StoreId { get; set; }
        public long Itm_No { get; set; }
        public Nullable<long> Limit_Qty { get; set; }
        public System.DateTime Updt_Date { get; set; }
    }
}
