//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSalReqdtl
    {
        public short StoreID { get; set; }
        public short Doc_Ty { get; set; }
        public long Doc_No { get; set; }
        public short Ln_No { get; set; }
        public Nullable<short> Dlv_Stor { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_DtAr { get; set; }
        public Nullable<long> Custm_Inv { get; set; }
        public Nullable<short> Reftyp_No { get; set; }
        public Nullable<long> Ref_No { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public Nullable<short> To_Store { get; set; }
        public Nullable<short> Mrkt_No { get; set; }
        public Nullable<short> Period_Time { get; set; }
        public Nullable<int> Slm_No { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<short> City_No { get; set; }
        public Nullable<long> Cstm_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<long> Catg_No { get; set; }
        public Nullable<int> Kind_No { get; set; }
        public Nullable<long> Itm_No { get; set; }
        public Nullable<short> Loc_No { get; set; }
        public string Itm_RefNo { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public Nullable<int> UnitLn_No { get; set; }
        public Nullable<int> Unit_ratio { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Dlv_Qty { get; set; }
        public string Exp_Date { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Itm_Cost { get; set; }
        public Nullable<decimal> Itm_Sal { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> Titm_Val { get; set; }
        public Nullable<decimal> Titm_Cost { get; set; }
        public Nullable<decimal> Titm_Sal { get; set; }
        public Nullable<decimal> Titm_Pur { get; set; }
        public Nullable<decimal> Disc1_Val { get; set; }
        public Nullable<decimal> Disc2_Val { get; set; }
        public Nullable<decimal> Othr_Disc { get; set; }
        public Nullable<decimal> Disc1_Prct { get; set; }
        public Nullable<decimal> Disc2_Prct { get; set; }
        public Nullable<decimal> Itm_SalSubUnt { get; set; }
        public Nullable<decimal> Itm_SalSubUnt2 { get; set; }
        public Nullable<decimal> Itm_SalSubUnt3 { get; set; }
        public Nullable<decimal> Bonus_Qty { get; set; }
        public Nullable<decimal> Bonus_Val { get; set; }
        public Nullable<decimal> Bonus_Prct { get; set; }
        public Nullable<decimal> BonusPur_Qty { get; set; }
        public Nullable<decimal> BonusPur_Val { get; set; }
        public Nullable<decimal> BonusPur_Prct { get; set; }
        public Nullable<decimal> DiscSal_Prct { get; set; }
        public Nullable<decimal> DiscSal2_prct { get; set; }
        public Nullable<decimal> BonusSalCrdt_Prct { get; set; }
        public Nullable<short> BonusSalCash_Prct { get; set; }
        public Nullable<short> Itm_Rcpt_Hold { get; set; }
        public Nullable<decimal> Customs_Prct { get; set; }
        public Nullable<decimal> Customs { get; set; }
        public Nullable<decimal> FcItm_Sal { get; set; }
        public Nullable<decimal> FcItm_Pur { get; set; }
        public Nullable<decimal> FcTitm_Val { get; set; }
        public Nullable<decimal> FcTitm_Cost { get; set; }
        public Nullable<decimal> FcTitm_Sal { get; set; }
        public Nullable<decimal> FcTitm_Pur { get; set; }
        public Nullable<decimal> SExpens { get; set; }
        public Nullable<decimal> Pur_Exp { get; set; }
        public Nullable<decimal> Othr_Price1 { get; set; }
        public Nullable<decimal> Othr_Price2 { get; set; }
        public Nullable<decimal> Titm_OPrice { get; set; }
        public Nullable<decimal> Ret_Qty { get; set; }
        public Nullable<decimal> Ret_Val { get; set; }
        public Nullable<decimal> Ret_Uprice { get; set; }
        public Nullable<decimal> Reord_Blnc { get; set; }
        public Nullable<decimal> Bal_Qty { get; set; }
        public Nullable<decimal> Bal_Val { get; set; }
        public Nullable<decimal> Itm_Blnc { get; set; }
        public Nullable<decimal> Itm_BlncCost { get; set; }
        public Nullable<short> User_Id { get; set; }
        public string Qty_Print { get; set; }
        public string updt_date { get; set; }
    }
}
