//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSalReqhdr
    {
        public short StoreID { get; set; }
        public short Doc_Ty { get; set; }
        public long Doc_No { get; set; }
        public Nullable<short> Dlv_Stor { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_DtAr { get; set; }
        public string RcvngPur_Dt { get; set; }
        public Nullable<System.DateTime> Pym_Dt { get; set; }
        public Nullable<long> Custm_Inv { get; set; }
        public Nullable<short> Reftyp_No { get; set; }
        public Nullable<long> Ref_No { get; set; }
        public Nullable<long> Ref_No2 { get; set; }
        public Nullable<short> To_Store { get; set; }
        public Nullable<short> Mrkt_No { get; set; }
        public Nullable<short> Period_Time { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public Nullable<short> City_No { get; set; }
        public Nullable<short> Slm_No { get; set; }
        public Nullable<long> Cstm_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public string Sup_Inv { get; set; }
        public string SubCstm_Filno { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Curncy_No { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> Tot_Sal { get; set; }
        public Nullable<decimal> Tot_Pur { get; set; }
        public Nullable<decimal> Tot_Cost { get; set; }
        public Nullable<decimal> Tot_Disc { get; set; }
        public Nullable<decimal> Tot_Prct { get; set; }
        public Nullable<decimal> Tot_ODisc { get; set; }
        public Nullable<decimal> Tot_OPrct { get; set; }
        public Nullable<decimal> Tot_customs { get; set; }
        public Nullable<decimal> Tot_Expens { get; set; }
        public Nullable<decimal> Tot_Exp { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Return_Mony { get; set; }
        public Nullable<decimal> Bonus_val { get; set; }
        public Nullable<decimal> FcTot_Sal { get; set; }
        public Nullable<decimal> FcTot_Pur { get; set; }
        public Nullable<decimal> FcTot_Cost { get; set; }
        public Nullable<decimal> FcTot_Disc { get; set; }
        public Nullable<decimal> FcTot_ODisc { get; set; }
        public Nullable<decimal> FcNet { get; set; }
        public Nullable<decimal> SExpens { get; set; }
        public Nullable<decimal> Expens1 { get; set; }
        public Nullable<decimal> Expens2 { get; set; }
        public Nullable<decimal> Expens3 { get; set; }
        public Nullable<decimal> Expens4 { get; set; }
        public Nullable<decimal> Expens5 { get; set; }
        public Nullable<decimal> Expens6 { get; set; }
        public Nullable<decimal> Expens7 { get; set; }
        public string Sup_VchrNo { get; set; }
        public Nullable<int> Credit_Days { get; set; }
        public string Dlv_Ord_No { get; set; }
        public Nullable<short> Ret_Status { get; set; }
        public Nullable<long> JV_No { get; set; }
        public Nullable<short> JV_Lno { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<short> Doc_Procs { get; set; }
        public Nullable<short> Doc_RProcs { get; set; }
        public string Doc_Post { get; set; }
        public string Trnf_Post { get; set; }
        public string GL_Post { get; set; }
        public Nullable<decimal> Rcpt_Value { get; set; }
        public Nullable<short> User_Id { get; set; }
        public string Doc_Time { get; set; }
        public Nullable<short> Print_No { get; set; }
        public Nullable<decimal> Tpur_Exp { get; set; }
        public Nullable<decimal> Tothr_Price { get; set; }
        public string updt_date { get; set; }
        public Nullable<long> Acc_InvAdj { get; set; }
    }
}
