//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItmsMfsunit
    {
        public int Actvty_No { get; set; }
        public int Cstm_Agrmnt { get; set; }
        public long Itm_No { get; set; }
        public short Ln_No { get; set; }
        public short Unit_No { get; set; }
        public Nullable<decimal> Unit_Ratio { get; set; }
        public Nullable<decimal> Unit_Pur { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Unit_Sal1 { get; set; }
        public Nullable<decimal> Unit_Sal2 { get; set; }
        public Nullable<decimal> Unit_Sal3 { get; set; }
        public Nullable<decimal> Unit_Sal4 { get; set; }
        public Nullable<decimal> Unit_Discval { get; set; }
        public Nullable<decimal> Unit_DiscPrct { get; set; }
        public string Updt_Date { get; set; }
        public Nullable<decimal> Unit_SalMain { get; set; }
    }
}
