//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lang_Forms
    {
        public int FormId { get; set; }
        public string FormName { get; set; }
        public string EN { get; set; }
        public string AR { get; set; }
        public Nullable<bool> GridFlg { get; set; }
        public Nullable<bool> TabFlg { get; set; }
        public Nullable<bool> ToolBarFlg { get; set; }
        public Nullable<bool> MenuFlg { get; set; }
    }
}
