//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCexpensDtl
    {
        public short StoreID { get; set; }
        public short Doc_Ty { get; set; }
        public long Doc_No { get; set; }
        public short Ln_No { get; set; }
        public string Lc_No { get; set; }
        public Nullable<int> JobOrd_Year { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_Dtar { get; set; }
        public Nullable<short> Pym_Type { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public Nullable<int> Cstm_No { get; set; }
        public Nullable<int> Sup_No { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<long> ICost_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Tr_Dsc1 { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public string Trnf_Post { get; set; }
        public Nullable<short> User_Id { get; set; }
        public Nullable<long> Jv_No { get; set; }
        public Nullable<short> Jv_Lno { get; set; }
    }
}
