//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCexpensHdr
    {
        public short StoreID { get; set; }
        public short Doc_Ty { get; set; }
        public long Doc_No { get; set; }
        public string Lc_No { get; set; }
        public Nullable<int> JobOrd_Year { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_DtAr { get; set; }
        public Nullable<short> Pym_Type { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public Nullable<System.DateTime> Pym_Dt { get; set; }
        public Nullable<int> Cstm_No { get; set; }
        public Nullable<int> Sup_No { get; set; }
        public Nullable<short> Ac_Ty { get; set; }
        public Nullable<decimal> Tot_Exp { get; set; }
        public Nullable<decimal> Tot_Val { get; set; }
        public Nullable<decimal> Tot_Cost { get; set; }
        public Nullable<decimal> Othr_Disc { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<short> Curncy_No { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<short> User_Id { get; set; }
        public string Doc_Time { get; set; }
        public Nullable<short> Doc_Procs { get; set; }
        public string Doc_Post { get; set; }
        public string Trnf_Post { get; set; }
        public string GL_Post { get; set; }
        public Nullable<short> Print_No { get; set; }
        public Nullable<long> Jv_No { get; set; }
        public Nullable<short> Jv_Lno { get; set; }
        public string Sup_Inv { get; set; }
        public string Sup_Inv2 { get; set; }
        public Nullable<int> Credit_Days { get; set; }
        public string Notes { get; set; }
    }
}
