//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCItemexp
    {
        public short ICost_No { get; set; }
        public string ICost_NmEN { get; set; }
        public string ICost_NmAR { get; set; }
        public Nullable<long> Acc_No { get; set; }
    }
}
