//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LcItmTrs
    {
        public short StoreID { get; set; }
        public long Doc_No { get; set; }
        public short Ln_No { get; set; }
        public string Lc_No { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_DtAr { get; set; }
        public Nullable<long> Custm_Inv { get; set; }
        public Nullable<long> Ref_No { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<long> Catg_No { get; set; }
        public Nullable<int> Kind_No { get; set; }
        public Nullable<long> Itm_No { get; set; }
        public Nullable<short> Loc_No { get; set; }
        public string Itm_RefNo { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public Nullable<int> UnitLn_No { get; set; }
        public Nullable<int> Unit_ratio { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Exp_Date { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Itm_Cost { get; set; }
        public Nullable<decimal> Itm_Sal { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> Titm_Val { get; set; }
        public Nullable<decimal> Titm_Cost { get; set; }
        public Nullable<decimal> Titm_Sal { get; set; }
        public Nullable<decimal> Titm_Pur { get; set; }
        public Nullable<decimal> Pur_Exp { get; set; }
        public string updt_date { get; set; }
    }
}
