//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCmpnam
    {
        public short Cmp_No { get; set; }
        public Nullable<short> Cmp_Activity { get; set; }
        public Nullable<short> Hijri_DifDay { get; set; }
        public Nullable<short> Brch_Trns { get; set; }
        public Nullable<short> Stor_Trns { get; set; }
        public Nullable<short> Main_Brn { get; set; }
        public Nullable<short> DLv_Stor { get; set; }
        public Nullable<short> Slm_No { get; set; }
        public Nullable<short> Local_Lang { get; set; }
        public Nullable<short> Sys_SetupNo { get; set; }
        public string Cmp_ShrtNm { get; set; }
        public Nullable<short> Itm_twice { get; set; }
        public Nullable<short> InvTrf_Disc1 { get; set; }
        public Nullable<short> InvTrf_Bouns { get; set; }
        public Nullable<short> BarCodeTy { get; set; }
        public Nullable<short> CostCalc { get; set; }
        public Nullable<short> Repeate_Item { get; set; }
        public Nullable<short> Disc2Pur_Dis2Sal { get; set; }
        public Nullable<short> ReqLocBalance { get; set; }
        public Nullable<short> Pur_TabOrder { get; set; }
        public Nullable<short> Start_Month { get; set; }
        public Nullable<short> Start_Year { get; set; }
        public Nullable<short> End_Month { get; set; }
        public Nullable<short> End_year { get; set; }
        public Nullable<short> Start_MonthHij { get; set; }
        public Nullable<short> Start_YearHij { get; set; }
        public Nullable<short> End_MonthHij { get; set; }
        public Nullable<short> End_yearHij { get; set; }
        public string Cmp_Nm { get; set; }
        public string Cmp_Nm2 { get; set; }
        public string Cmp_Tel { get; set; }
        public string Cmp_Fax { get; set; }
        public string Cmp_Email { get; set; }
        public string Cmp_Add { get; set; }
        public string Cmp_Eadd { get; set; }
        public string Cmp_Enm { get; set; }
        public string Cmp_Enm2 { get; set; }
        public string Prnt_Forms { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<bool> DelivaryStratigy { get; set; }
        public Nullable<bool> CostCenterStratigy { get; set; }
        public int Activ_typ_no { get; set; }
        public Nullable<short> Cshr_Status { get; set; }
        public Nullable<short> Cshr_Spr { get; set; }
        public Nullable<short> Sal_Spr { get; set; }
        public Nullable<short> Pur_Spr { get; set; }
        public Nullable<short> Invty_Spr { get; set; }
        public Nullable<short> Srv_Status { get; set; }
        public Nullable<short> Dnv_Status { get; set; }
        public Nullable<short> SalB_Dn { get; set; }
        public Nullable<short> PurB_Srv { get; set; }
        public Nullable<short> Itm_SrchRef { get; set; }
        public Nullable<short> Date_Status { get; set; }
        public Nullable<short> Dn_woCost { get; set; }
        public Nullable<short> Srv_woCost { get; set; }
        public Nullable<bool> Same_Brn_DB { get; set; }
        public Nullable<short> Brch_Comm { get; set; }
        public Nullable<short> Month_Post1 { get; set; }
        public Nullable<short> Month_Post2 { get; set; }
        public Nullable<short> Month_Post3 { get; set; }
        public Nullable<short> Month_Post4 { get; set; }
        public Nullable<short> Month_Post5 { get; set; }
        public Nullable<short> Month_Post6 { get; set; }
        public Nullable<short> Month_Post7 { get; set; }
        public Nullable<short> Month_Post8 { get; set; }
        public Nullable<short> Month_Post9 { get; set; }
        public Nullable<short> Month_Post10 { get; set; }
        public Nullable<short> Month_Post11 { get; set; }
        public Nullable<short> Month_Post12 { get; set; }
        public Nullable<short> Sal_Slip_Spcinv { get; set; }
        public Nullable<int> ModemPortNo { get; set; }
        public string ModemTelNo { get; set; }
        public Nullable<int> ChunkSize { get; set; }
        public Nullable<int> JvAuto_Mnth { get; set; }
        public Nullable<int> SalInv_Cash { get; set; }
        public Nullable<int> PurInv_Cash { get; set; }
        public Nullable<int> GL_NetSale { get; set; }
        public Nullable<short> GL_NetPur { get; set; }
        public Nullable<int> WoBoRpt { get; set; }
        public Nullable<int> PrintOrder { get; set; }
        public Nullable<int> Pur_Disc1 { get; set; }
        public Nullable<int> Sal_Disc1 { get; set; }
        public Nullable<int> Pur_Disc2 { get; set; }
        public Nullable<int> Sal_Disc2 { get; set; }
        public Nullable<int> Sal_Bouns { get; set; }
        public Nullable<int> Pur_Bouns { get; set; }
        public Nullable<int> Batch_No { get; set; }
        public Nullable<int> Disc1Pur_Dis1Sal { get; set; }
        public Nullable<int> NoStock { get; set; }
        public Nullable<int> Gl_Salesman { get; set; }
        public Nullable<int> Sec_Salesman { get; set; }
        public Nullable<int> Warehouse { get; set; }
        public Nullable<int> Inv_Sequence { get; set; }
        public Nullable<int> Sales_Type { get; set; }
        public Nullable<int> Activity_Type { get; set; }
        public string CR_No { get; set; }
        public string CC_No { get; set; }
        public string Tax_No { get; set; }
        public Nullable<decimal> TaxExtra_Prct { get; set; }
    }
}
