//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainBranch2
    {
        public int Cmp_No { get; set; }
        public int Brn_No { get; set; }
        public Nullable<short> Main_Brn { get; set; }
        public Nullable<short> Dlv_Stor { get; set; }
        public Nullable<short> Actvty_No { get; set; }
        public string Isue_ALinvc { get; set; }
        public Nullable<short> Allow_StoreTrs { get; set; }
        public string Br_Ty { get; set; }
        public string Brn_Nm { get; set; }
        public string Brn_NmAr { get; set; }
        public string Brn_Tel { get; set; }
        public string Brn_Fax { get; set; }
        public string Brn_Adrs { get; set; }
        public string Brn_Email { get; set; }
        public string Brn_Foldr { get; set; }
        public Nullable<int> Fcstm_No { get; set; }
        public Nullable<int> Tcstm_No { get; set; }
        public Nullable<int> Cstm_No { get; set; }
        public Nullable<long> Acc_Customer { get; set; }
        public Nullable<long> Acc_Suplier { get; set; }
        public Nullable<long> Acc_Cashier { get; set; }
        public Nullable<long> Acc_Customer1 { get; set; }
        public Nullable<long> Acc_Suplier1 { get; set; }
        public Nullable<long> Acc_Suplier2 { get; set; }
        public Nullable<long> Acc_Sales { get; set; }
        public Nullable<long> Acc_RetSal { get; set; }
        public Nullable<long> Crdt_CshSalDiscAcc { get; set; }
        public Nullable<long> Crdt_BnusSalDiscAcc { get; set; }
        public Nullable<long> Csh_SalAcc { get; set; }
        public Nullable<long> Csh_RetsalAcc { get; set; }
        public Nullable<long> Csh_CshSalDiscAcc { get; set; }
        public Nullable<long> Csh_BnusSalDiscAcc { get; set; }
        public Nullable<long> Cmp_PurchaseAcc { get; set; }
        public Nullable<long> Cmp_RetPurchAcc { get; set; }
        public Nullable<long> Cmp_CshPurDiscAcc { get; set; }
        public Nullable<long> Cmp_BnusPurDiscAcc { get; set; }
        public Nullable<long> Agnt_PurchaseAcc { get; set; }
        public Nullable<long> Agnt_RetPurchAcc { get; set; }
        public Nullable<long> Agnt_CshPurDiscAcc { get; set; }
        public Nullable<long> Agnt_BnusPurDiscAcc { get; set; }
        public Nullable<long> Othr_PurchaseAcc { get; set; }
        public Nullable<long> Othr_RetPurchAcc { get; set; }
        public Nullable<long> Othr_CshPurDiscAcc { get; set; }
        public Nullable<long> Othr_BnusPurDiscAcc { get; set; }
        public Nullable<short> DlyPst_CshSal { get; set; }
        public Nullable<short> DlyPst_CshPur { get; set; }
        public Nullable<long> Adv_SalAcc { get; set; }
        public Nullable<long> Adv_RetSalAcc { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<long> Csh_PurAcc { get; set; }
        public Nullable<long> Csh_RetPurAcc { get; set; }
        public Nullable<decimal> Inv_Prdctn { get; set; }
        public Nullable<decimal> Inv_Undprs { get; set; }
        public Nullable<decimal> Inv_RM { get; set; }
        public Nullable<long> Cost_SalInvt { get; set; }
        public Nullable<long> Cost_INVt { get; set; }
        public Nullable<long> Acc_InvAdj { get; set; }
        public Nullable<long> Acc_Cashier1 { get; set; }
        public Nullable<long> Acc_Cashier2 { get; set; }
        public Nullable<long> Acc_Cashier3 { get; set; }
        public Nullable<long> Acc_PNO { get; set; }
        public Nullable<long> Acc_Cheque { get; set; }
        public Nullable<long> Acc_TaxExtraDb { get; set; }
        public Nullable<long> Acc_TaxExtraCR { get; set; }
    }
}
