//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainBranchDlv2
    {
        public int Brn_No { get; set; }
        public int Dlv_Stor { get; set; }
        public string Dlv_NmAr { get; set; }
        public string Dlv_NmEn { get; set; }
    }
}
