//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsCcustmr
    {
        public short Brn_No { get; set; }
        public long Cstm_No { get; set; }
        public Nullable<short> Cstm_Active { get; set; }
        public Nullable<short> Cstm_Ctg { get; set; }
        public string Cstm_Refno { get; set; }
        public Nullable<int> Prnt_cstm { get; set; }
        public Nullable<int> Level_no { get; set; }
        public Nullable<bool> Have_sub { get; set; }
        public Nullable<bool> Main { get; set; }
        public Nullable<short> Internal_Invoice { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<short> Catg_No { get; set; }
        public Nullable<long> Acc_ArAp { get; set; }
        public string Cstm_Nm { get; set; }
        public string Cstm_Nmarb { get; set; }
        public Nullable<int> Slm_No { get; set; }
        public Nullable<int> Mrkt_No { get; set; }
        public Nullable<short> Nutr_No { get; set; }
        public Nullable<int> Cntry_No { get; set; }
        public Nullable<short> City_No { get; set; }
        public Nullable<int> Area_No { get; set; }
        public Nullable<decimal> Credit_Value { get; set; }
        public Nullable<int> Credit_Days { get; set; }
        public string Cstm_Adr { get; set; }
        public string Cstm_POBox { get; set; }
        public string Cstm_ZipCode { get; set; }
        public string Cstm_Rsp { get; set; }
        public string Cstm_Othr { get; set; }
        public string Cstm_Email { get; set; }
        public string Cstm_Tel { get; set; }
        public string Cstm_Fax { get; set; }
        public string Cntct_Prsn1 { get; set; }
        public string Cntct_Prsn2 { get; set; }
        public string Cntct_Prsn3 { get; set; }
        public string Cntct_Prsn4 { get; set; }
        public string Cntct_Prsn5 { get; set; }
        public string TitL1 { get; set; }
        public string TitL2 { get; set; }
        public string TitL3 { get; set; }
        public string TitL4 { get; set; }
        public string TitL5 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Mobile4 { get; set; }
        public string Mobile5 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Email4 { get; set; }
        public string Email5 { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<decimal> CBal { get; set; }
        public Nullable<decimal> BalAgL30 { get; set; }
        public Nullable<decimal> BalAgG30 { get; set; }
        public Nullable<decimal> BalAgG60 { get; set; }
        public Nullable<decimal> BalAgG90 { get; set; }
        public Nullable<decimal> BalAgG120 { get; set; }
        public Nullable<decimal> BalAgG150 { get; set; }
        public Nullable<decimal> BalAgG180 { get; set; }
        public Nullable<decimal> BalAgG270 { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> Fbal_Rcpt { get; set; }
        public Nullable<short> Custmr_Scope { get; set; }
        public string Opn_Date { get; set; }
        public string Opn_Time { get; set; }
        public string User_ID { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public Nullable<int> Cstm_Agrmnt { get; set; }
        public Nullable<decimal> Disc_prct { get; set; }
        public Nullable<short> Itm_Sal { get; set; }
        public Nullable<decimal> Fbal_BalAgL30 { get; set; }
        public Nullable<decimal> Fbal_BalAgG30 { get; set; }
        public Nullable<decimal> Fbal_BalAgG60 { get; set; }
        public Nullable<decimal> Fbal_BalAgG90 { get; set; }
        public Nullable<decimal> Fbal_BalAgG120 { get; set; }
        public Nullable<decimal> Fbal_BalAgG150 { get; set; }
        public Nullable<decimal> Fbal_BalAgG180 { get; set; }
        public Nullable<decimal> Fbal_BalAgG270 { get; set; }
        public Nullable<long> Linv_No { get; set; }
        public string Linv_Dt { get; set; }
        public Nullable<decimal> Linv_Net { get; set; }
        public Nullable<long> LRcpt_No { get; set; }
        public string LRcpt_Dt { get; set; }
        public Nullable<decimal> LRcpt_Db { get; set; }
        public Nullable<decimal> Inv_Sales { get; set; }
        public Nullable<decimal> Inv_SalesRet { get; set; }
        public Nullable<short> DeserveDiscounts { get; set; }
        public string Notes { get; set; }
        public Nullable<long> ParentAcc_No { get; set; }
        public Nullable<short> AgeNotCalculate { get; set; }
        public string Tax_No { get; set; }
    }
}
