//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsEmpcntrct
    {
        public long Emp_No { get; set; }
        public string Emp_NmAr { get; set; }
        public string Emp_NmEn { get; set; }
        public string Emp_Sex { get; set; }
        public string Cnt_Stdt { get; set; }
        public string Cnt_Nwdt { get; set; }
        public string Cnt_Endt { get; set; }
        public Nullable<short> Tkt_No { get; set; }
        public string Tkt_Fraqncy { get; set; }
        public Nullable<short> Tkt_Adult { get; set; }
        public Nullable<short> Tkt_Child { get; set; }
        public string Tkt_Class { get; set; }
        public string Tkt_Destn { get; set; }
        public string Tkt_Sector { get; set; }
        public Nullable<decimal> Bsc_Salary { get; set; }
        public Nullable<decimal> Hous_Alw { get; set; }
        public Nullable<decimal> Trnsp_Alw { get; set; }
        public Nullable<decimal> Other_Alw { get; set; }
        public string Emp_Vactn { get; set; }
        public string Emp_Acntno { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public Nullable<short> Depm_No { get; set; }
        public Nullable<short> Job_No { get; set; }
        public Nullable<short> Cntyp_No { get; set; }
        public Nullable<short> Pymnt_No { get; set; }
        public Nullable<long> Bnk_No { get; set; }
        public Nullable<short> Wrkstu_No { get; set; }
        public Nullable<long> Sub_Bnk { get; set; }
        public string Bnk_Brn { get; set; }
        public Nullable<int> Car_No { get; set; }
        public Nullable<short> Depm_No1 { get; set; }
        public Nullable<decimal> Wrk_Hour { get; set; }
        public Nullable<decimal> Wrk_CostHour { get; set; }
        public string Wrk_OvrTime { get; set; }
        public Nullable<int> Cmp_No { get; set; }
        public Nullable<int> Gov_Cntrct { get; set; }
        public string Job_Date { get; set; }
        public Nullable<short> Food_Alw { get; set; }
        public Nullable<decimal> Blnc_Paid { get; set; }
        public Nullable<decimal> Blnc_UnPaid { get; set; }
        public Nullable<short> salry_typ { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<long> Acc_NoDb1 { get; set; }
        public Nullable<long> Acc_NoDb2 { get; set; }
        public Nullable<long> Acc_NoCr1 { get; set; }
        public Nullable<long> Acc_NoCr2 { get; set; }
        public Nullable<long> Acc_Loans { get; set; }
        public Nullable<decimal> Salry_Cost1 { get; set; }
        public Nullable<decimal> Salry_Cost2 { get; set; }
        public Nullable<int> Shift_Type { get; set; }
        public Nullable<float> Lunch_hour { get; set; }
    }
}
