//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsEmpadmin
    {
        public long Emp_No { get; set; }
        public string Emp_NOt { get; set; }
        public string Emp_Nm1 { get; set; }
        public string Emp_Nm2 { get; set; }
        public string Emp_Nm3 { get; set; }
        public string Emp_Nm4 { get; set; }
        public string Emp_Nm5 { get; set; }
        public string Emp_Nm { get; set; }
        public string Emp_Nme1 { get; set; }
        public string Emp_Nme2 { get; set; }
        public string Emp_Nme3 { get; set; }
        public string Emp_Nme4 { get; set; }
        public string Emp_Nme5 { get; set; }
        public string Emp_Nme { get; set; }
        public string Birth_Plac { get; set; }
        public Nullable<short> Reljan { get; set; }
        public Nullable<short> Educt_Type { get; set; }
        public string Birth_Date { get; set; }
        public string Uniq_no { get; set; }
        public string Work_Expyer { get; set; }
        public string Blood_Type { get; set; }
        public string Pasprt_Nt { get; set; }
        public string Pasprt_Plc { get; set; }
        public Nullable<short> Status_Type { get; set; }
        public string Pasprt_No { get; set; }
        public string Pasprt_Sdt { get; set; }
        public string Pasprt_Edt { get; set; }
        public Nullable<int> Pasprt_Ty { get; set; }
        public string Residn_No { get; set; }
        public Nullable<short> Residn_Ty { get; set; }
        public string Civl_No { get; set; }
        public Nullable<short> Residn_Plc { get; set; }
        public string Residn_Chld { get; set; }
        public string Residn_Sdt { get; set; }
        public string Residn_Edt { get; set; }
        public Nullable<short> Job_Stu { get; set; }
        public string Job_Date { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string Work_Lic { get; set; }
        public string Work_Period { get; set; }
        public string Work_StDt { get; set; }
        public string Work_Endt { get; set; }
        public Nullable<float> Month_Salry { get; set; }
        public Nullable<float> MMonth_Salry { get; set; }
        public string Entr_Date { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public string Ownr_Near { get; set; }
        public string Pasp_Endt { get; set; }
        public string Rsdn_Endt { get; set; }
        public string Emp_Zipnm { get; set; }
        public string Emp_Tel { get; set; }
        public string Emp_Zipno { get; set; }
        public string Emp_Pbox { get; set; }
        public string Gender { get; set; }
        public Nullable<short> Depm_No { get; set; }
        public Nullable<short> Job_No { get; set; }
        public Nullable<short> MJob_No { get; set; }
        public Nullable<int> Issu_Lic { get; set; }
        public Nullable<short> Ownr_No { get; set; }
        public Nullable<short> Emp_Adrsno { get; set; }
        public string Depm_Civlno { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Psprt_Rcv { get; set; }
        public Nullable<int> Basic_Temp { get; set; }
        public Nullable<int> Int_Ext { get; set; }
        public Nullable<int> Specl_Need { get; set; }
        public Nullable<int> Specl_NeedTyp { get; set; }
        public string Lic_No { get; set; }
        public Nullable<int> Lic_Typ { get; set; }
        public Nullable<int> Lic_Plc { get; set; }
        public string Lic_Sdt { get; set; }
        public string Lic_Edt { get; set; }
        public Nullable<int> Gov_Cntrct { get; set; }
        public Nullable<short> Cmp_No { get; set; }
        public Nullable<int> Dpm_No { get; set; }
        public Nullable<int> Hldy_Typ { get; set; }
        public Nullable<int> Hldy_Period { get; set; }
        public Nullable<int> Prev_Blnc { get; set; }
        public string Emp_Ref { get; set; }
        public string On_WorkDt { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<short> Loc_No { get; set; }
        public string Insurance_No { get; set; }
        public Nullable<short> Budg_typ { get; set; }
        public string Insur_StartDt { get; set; }
        public string Insur_EndDt { get; set; }
        public Nullable<decimal> Insur_BSalry { get; set; }
        public Nullable<decimal> Insur_ReSTSalry { get; set; }
        public Nullable<short> post { get; set; }
        public Nullable<long> Acc_NoDb1 { get; set; }
        public Nullable<long> Acc_NoDb2 { get; set; }
        public Nullable<long> Acc_NoCr1 { get; set; }
        public Nullable<long> Acc_NoCr2 { get; set; }
        public Nullable<long> Acc_Loans { get; set; }
        public Nullable<decimal> Salry_Cost1 { get; set; }
        public Nullable<decimal> Salry_Cost2 { get; set; }
        public Nullable<decimal> Fbal_DB { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
    }
}
