//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsItmmfs
    {
        public long Itm_No { get; set; }
        public Nullable<short> Itm_Active { get; set; }
        public string Ref_No { get; set; }
        public Nullable<long> Catg_No { get; set; }
        public Nullable<int> Kind_No { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public Nullable<short> UnitPur_No { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<int> Measure_Grp { get; set; }
        public string Itm_NmEn { get; set; }
        public string Itm_NmAr { get; set; }
        public Nullable<int> Req_Limit { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> Itm_COst { get; set; }
        public Nullable<decimal> Itm_Sal1 { get; set; }
        public Nullable<decimal> Itm_Sal2 { get; set; }
        public Nullable<decimal> Itm_Sal3 { get; set; }
        public Nullable<decimal> Itm_Sal4 { get; set; }
        public Nullable<decimal> Itm_Sal5 { get; set; }
        public Nullable<decimal> Itm_Sal6 { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Pur_Bouns { get; set; }
        public Nullable<decimal> Sal_Bouns { get; set; }
        public string Itm_Othr { get; set; }
        public Nullable<short> Exp_Date { get; set; }
        public string Item_BarCode { get; set; }
        public string Fctry_Barcode { get; set; }
        public Nullable<short> Medcn_Grup1 { get; set; }
        public Nullable<short> Medcn_Grup2 { get; set; }
        public Nullable<short> Genric_No { get; set; }
        public Nullable<short> Bouns_Chk { get; set; }
        public Nullable<decimal> Bouns_Qty { get; set; }
        public Nullable<short> Disc1_Chk { get; set; }
        public Nullable<short> Disc2_Chk { get; set; }
        public Nullable<short> Disc3_Chk { get; set; }
        public Nullable<short> Disc4_Chk { get; set; }
        public Nullable<short> Disc5_Chk { get; set; }
        public Nullable<decimal> Disc1_Prct { get; set; }
        public Nullable<decimal> Disc2_Prct { get; set; }
        public Nullable<decimal> Disc3_Prct { get; set; }
        public Nullable<decimal> Disc4_Prct { get; set; }
        public Nullable<decimal> Disc5_Prct { get; set; }
        public Nullable<decimal> Unit_Pur { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Unit_Sal1 { get; set; }
        public Nullable<decimal> Unit_Sal2 { get; set; }
        public Nullable<decimal> Unit_Sal3 { get; set; }
        public Nullable<decimal> Unit_Sal4 { get; set; }
        public Nullable<decimal> Unit_Sal5 { get; set; }
        public Nullable<decimal> Unit_Sal6 { get; set; }
        public Nullable<decimal> Unit_Sal7 { get; set; }
        public Nullable<decimal> Unit_Sal8 { get; set; }
        public Nullable<decimal> Unit_Sal9 { get; set; }
        public Nullable<decimal> Unit_Sal10 { get; set; }
        public Nullable<decimal> Unit_Discval { get; set; }
        public Nullable<decimal> Unit_DiscPrct { get; set; }
        public string Shelf_No { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Updt_Date { get; set; }
        public string Batch_No { get; set; }
        public Nullable<short> Qty2_Chk { get; set; }
        public Nullable<short> Qty3_Chk { get; set; }
        public Nullable<short> Pckng_Unit { get; set; }
        public Nullable<short> Pckng_Ratio { get; set; }
        public Nullable<decimal> Itm_TWeight { get; set; }
        public Nullable<decimal> Itm_NWeight { get; set; }
        public Nullable<short> MaxQty_SaL { get; set; }
        public Nullable<decimal> Taxp_Extra { get; set; }
        public Nullable<short> Tax_Allow { get; set; }
        public string Itm_Length { get; set; }
        public string Itm_Width { get; set; }
        public string Itm_Height { get; set; }
        public string Itm_Durability { get; set; }
        public Nullable<decimal> ChkDiscount { get; set; }
        public Nullable<decimal> Commission { get; set; }
    }
}
