//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsLC
    {
        public short StoreID { get; set; }
        public long Doc_No { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public string Doc_DtAr { get; set; }
        public Nullable<short> Pym_No { get; set; }
        public string Pym_Terms { get; set; }
        public string Lc_No { get; set; }
        public Nullable<int> Bank_No { get; set; }
        public string Lc_OpnDt { get; set; }
        public string Lc_OpnDAr { get; set; }
        public string Lc_CLosDt { get; set; }
        public string Lc_CLosDAr { get; set; }
        public Nullable<short> Curncy_No1 { get; set; }
        public Nullable<short> Curncy_No2 { get; set; }
        public Nullable<decimal> ExchangeRate1 { get; set; }
        public Nullable<decimal> ExchangeRate2 { get; set; }
        public Nullable<decimal> LC_FVAL { get; set; }
        public Nullable<decimal> LCExp_FVAL { get; set; }
        public Nullable<decimal> LC_VAL { get; set; }
        public Nullable<decimal> LCExp_VAL { get; set; }
        public string Po_No { get; set; }
        public string Po_Dt { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<long> Acc_Db { get; set; }
        public Nullable<decimal> TLC_Value { get; set; }
        public Nullable<decimal> TLc_exp { get; set; }
        public string ReqQut_No { get; set; }
        public string ReqQut_DT { get; set; }
        public string SupQut_No { get; set; }
        public string SupQut_Dt { get; set; }
        public string ShiVia { get; set; }
        public string Dlv_Period { get; set; }
        public string Dlv_PLC { get; set; }
        public Nullable<long> NoofItems { get; set; }
        public string Requesdt_By { get; set; }
        public string Used_By { get; set; }
        public Nullable<long> Tr_NoClose { get; set; }
        public Nullable<decimal> Fbal_Value { get; set; }
        public Nullable<decimal> Fbal_Expens { get; set; }
        public Nullable<decimal> Fbal_Customs { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_Cr { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> CBal { get; set; }
        public Nullable<decimal> AccTot_Exp { get; set; }
        public Nullable<decimal> AccTot_customs { get; set; }
        public Nullable<decimal> AccTot_Expens { get; set; }
        public Nullable<decimal> AccTot_Lc { get; set; }
        public string Lc_Post { get; set; }
        public string updt_date { get; set; }
        public Nullable<int> Kind_No { get; set; }
    }
}
