//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsSuplir
    {
        public Nullable<int> Brn_No { get; set; }
        public long Sup_No { get; set; }
        public string Sup_Refno { get; set; }
        public Nullable<short> SupCtg_No { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public string Sup_Nm { get; set; }
        public string Sup_NmAr { get; set; }
        public string Sup_Adr { get; set; }
        public string Sup_Rsp { get; set; }
        public string Sup_Othr { get; set; }
        public Nullable<short> Curncy_No { get; set; }
        public string Sup_Email { get; set; }
        public string Sup_Tel1 { get; set; }
        public string Sup_Tel2 { get; set; }
        public string Mobile { get; set; }
        public string Sup_Fax { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<decimal> Credit_Value { get; set; }
        public Nullable<int> Credit_Days { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<short> TradeOffer { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> CBal { get; set; }
        public Nullable<decimal> BalAgL30 { get; set; }
        public Nullable<decimal> BalAgG30 { get; set; }
        public Nullable<decimal> BalAgG60 { get; set; }
        public Nullable<decimal> BalAgG90 { get; set; }
        public Nullable<decimal> BalAgG120 { get; set; }
        public string Trnf_Post { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public string User_ID { get; set; }
        public Nullable<decimal> Fbal_BalAgL30 { get; set; }
        public Nullable<decimal> Fbal_BalAgG30 { get; set; }
        public Nullable<decimal> Fbal_BalAgG60 { get; set; }
        public Nullable<decimal> Fbal_BalAgG90 { get; set; }
        public Nullable<decimal> Fbal_BalAgG120 { get; set; }
        public Nullable<decimal> Fbal_Rcpt { get; set; }
        public string Tax_No { get; set; }
    }
}
