//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Controls
    {
        public string FormName { get; set; }
        public int id { get; set; }
        public string ControlEN { get; set; }
        public string ControlAR { get; set; }
        public string CnName { get; set; }
        public Nullable<decimal> Parent { get; set; }
        public string CtlTyp { get; set; }
        public string TipEN { get; set; }
        public string TipAR { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> leftAr { get; set; }
        public Nullable<int> leftEn { get; set; }
        public Nullable<int> pwidth { get; set; }
        public Nullable<int> ColIndex { get; set; }
        public bool Translatable { get; set; }
    }
}
