//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_MainMenu
    {
        public int MenuId { get; set; }
        public string MName { get; set; }
        public Nullable<int> MIndex { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CaptionAr { get; set; }
        public string CaptionEn { get; set; }
        public Nullable<int> HeadMenu { get; set; }
        public Nullable<int> WndFunction { get; set; }
        public string FormName { get; set; }
        public Nullable<int> HelpFileNo { get; set; }
    }
}
