//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Users
    {
        public int GroupId { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string User_NmAr { get; set; }
        public string User_NmEn { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Stor_Trns { get; set; }
        public Nullable<int> Brch_Trns { get; set; }
        public Nullable<int> Local_Lang { get; set; }
        public Nullable<int> Sal_Slip_Spcinv { get; set; }
        public Nullable<int> Cmp_Activity { get; set; }
        public string Br_Ty { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
