//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_GrpMenuPrvldg
    {
        public int GroupId { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> AccessFlag { get; set; }
        public Nullable<int> AccessLevel { get; set; }
    }
}
